apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.nodeName }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ .Values.nodeName }}
    chain: bsc
spec:
  serviceName: {{ .Values.nodeName }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.nodeName }}
  template:
    metadata:
      labels:
        app: {{ .Values.nodeName }}
        chain: bsc
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext }}
      securityContext:
        {{- if eq .Values.securityContext.apparmor "unconfined" }}
        appArmorProfile:
          type: Unconfined
        {{- end }}
      {{- end }}
      {{- if and .Values.snapshot .Values.snapshot.enabled }}
      initContainers:
      - name: download-snapshot
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          if [ ! -f /data/geth/chaindata/CURRENT ]; then
            echo "Downloading snapshot from {{ .Values.snapshot.url }}"
            wget -O /tmp/snapshot.tar.gz {{ .Values.snapshot.url }}
            {{- if .Values.snapshot.checksum }}
            echo "{{ .Values.snapshot.checksum }}  /tmp/snapshot.tar.gz" | sha256sum -c -
            {{- end }}
            echo "Extracting snapshot..."
            tar -xzf /tmp/snapshot.tar.gz -C /data
            rm /tmp/snapshot.tar.gz
            echo "Snapshot extraction complete"
          else
            echo "Chaindata already exists, skipping snapshot download"
          fi
        volumeMounts:
        - name: data
          mountPath: /data
      {{- end }}
      containers:
      - name: bsc
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - geth
          - --config=/bsc/config/config.toml
          - --datadir=/data
          - --http
          - --http.addr=0.0.0.0
          - --http.port={{ .Values.service.ports.http.port }}
          - --http.api={{ .Values.config.httpApi }}
          - --ws
          - --ws.addr=0.0.0.0
          - --ws.port={{ .Values.service.ports.ws.port }}
          - --cache={{ .Values.config.cache }}
          - --tries-verify-mode={{ .Values.config.triesVerifyMode }}
          - --gcmode={{ .Values.config.gcMode }}
          - --history.transactions={{ .Values.config.historyTransactions }}
          {{- if .Values.config.rpcAllowUnprotectedTxs }}
          - --rpc.allow-unprotected-txs
          {{- end }}
          - --syncmode={{ .Values.config.syncMode }}
          {{- if .Values.config.ipcDisable }}
          - --ipcdisable
          {{- end }}
          - --http.vhosts={{ .Values.config.httpVirtualHosts }}
          - --http.corsdomain={{ .Values.config.httpCorsOrigins }}
          {{- if .Values.networking }}
          - --maxpeers={{ .Values.networking.maxPeers }}
          {{- if .Values.networking.bootnodes }}
          - --bootnodes={{ .Values.networking.bootnodes }}
          {{- end }}
          - --nat={{ .Values.networking.nat }}
          {{- if not .Values.networking.nodeDiscovery }}
          - --nodiscover
          {{- end }}
          {{- end }}
          - --metrics
          - --metrics.addr=0.0.0.0
          - --metrics.port={{ .Values.service.ports.metrics.port }}
          - --pprof
          - --pprof.addr=0.0.0.0
          - --pprof.port={{ .Values.service.ports.metrics.port }}
          - --verbosity={{ .Values.config.verbosity }}
          {{- if .Values.config.txpool }}
          - --txpool.globalslots={{ .Values.config.txpool.globalslots }}
          - --txpool.globalqueue={{ .Values.config.txpool.globalqueue }}
          - --txpool.lifetime={{ .Values.config.txpool.lifetime }}
          {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.service.ports.http.port }}
          {{- if .Values.service.ports.http.hostPort }}
          hostPort: {{ .Values.service.ports.http.hostPort }}
          {{- end }}
          protocol: TCP
        - name: ws
          containerPort: {{ .Values.service.ports.ws.port }}
          {{- if .Values.service.ports.ws.hostPort }}
          hostPort: {{ .Values.service.ports.ws.hostPort }}
          {{- end }}
          protocol: TCP
        - name: metrics
          containerPort: {{ .Values.service.ports.metrics.port }}
          {{- if .Values.service.ports.metrics.hostPort }}
          hostPort: {{ .Values.service.ports.metrics.hostPort }}
          {{- end }}
          protocol: TCP
        - name: p2p
          containerPort: {{ .Values.service.ports.p2p.port }}
          {{- if .Values.service.ports.p2p.hostPort }}
          hostPort: {{ .Values.service.ports.p2p.hostPort }}
          {{- end }}
          protocol: TCP
        - name: p2p-udp
          containerPort: {{ .Values.service.ports.p2p.port }}
          {{- if .Values.service.ports.p2p.hostPort }}
          hostPort: {{ .Values.service.ports.p2p.hostPort }}
          {{- end }}
          protocol: UDP
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /debug/metrics
            port: metrics
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "curl -sf -X POST -H 'Content-Type: application/json' --data '{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":1}' http://localhost:{{ .Values.service.ports.http.port }} || exit 1"
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /bsc/config
          readOnly: true
        {{- with .Values.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if and .Values.monitoring .Values.monitoring.enabled .Values.monitoring.gethExporter.enabled }}
      # Geth Exporter Sidecar - Exposes Prometheus metrics from RPC
      - name: geth-exporter
        image: "{{ .Values.monitoring.gethExporter.image.repository }}:{{ .Values.monitoring.gethExporter.image.tag }}"
        imagePullPolicy: {{ .Values.monitoring.gethExporter.image.pullPolicy }}
        env:
        - name: GETH
          value: "{{ .Values.monitoring.gethExporter.rpcUrl }}"
        - name: DELAY
          value: "1000"
        ports:
        - name: exporter
          containerPort: {{ .Values.monitoring.gethExporter.port }}
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /metrics
            port: exporter
          initialDelaySeconds: 30
          periodSeconds: 10
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ .Values.nodeName }}-config
      {{- if not .Values.persistence.enabled }}
      - name: data
        hostPath:
          path: {{ .Values.persistence.hostPath }}
          type: DirectoryOrCreate
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.persistence.storageClass }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
  {{- end }}
